### ISSUE TITLE
Could you please upload the code a.s.a.p.

### ISSUE THREAD

**Issue by ChenBaiyang** [MaoXinn/MRAEA#1]
Dear Xin,

Greetings!
I've read your paper, it's a great inspiration to me. 
Could you please upload the code a.s.a.p.?

Thanks for your sharing.
Chen Baiyang

**Comment by MaoXinn** [comment]
The code is  available now.
Thanks for your attention~

**Comment by ChenBaiyang** [comment]
Thanks very much!
